import React from "react";
import Footer3 from "../footer/Footer3";
import Header from "../header/Header";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";
import ContactPage2 from "../contact/contactPage2";
import Notification from "../notification/notification";
import SubNavigation from "../Sub-Navbar/sub-navigation";

function Layout(props) {
  const contactProps = props?.children?.props?.children?.props?.children;
 const headerProps = props?.children?.props?.children?.props?.children;
  const footerProps = props?.children?.props?.children?.props?.children;
 


  var contactValue= ""; 
  if(contactProps){
  contactValue = contactProps[0]?.props?.uiSettings?.TH00150C06;
   }
//console.log("c",contactValue)

  var headerValue= ""; 
  if(headerProps){
  headerValue = headerProps[0]?.props?.uiSettings?.TH00150C01;
   }
 //console.log("h",headerProps)
  var footerValue= ""; 
    if(footerProps){
    footerValue = footerProps[0]?.props?.uiSettings?.TH00150C02;
     }

//  console.log(props);
//  console.log("FF",footerValue);

  useBodyClass("home-dark2");

  return (
    <>
     {/* <Head>
        <title>
          lumina- Software Agency and creative IT solution NEXTJS Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head> */}

      <Header header={headerValue}/>
      {/* <SubNavigation/> */}
      {props?.children}
      {/* <Notification/>  */}
      {/* {(!props?.contact) && (<ContactPage2 contact={contactValue} />)} */}
      <Footer3 footer={footerValue}/>
    </>
  );
}

export default Layout;
